# Generated by Django 6.0.3 on 2026-03-12 00:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_add_seat_label_remove_seat_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_combo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to='concessions.concessioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('order_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sales_channel', models.CharField(choices=[('KIOSK', 'Kiosk'), ('WEB', 'Web'), ('APP', 'App'), ('IN_SEAT', 'In-Seat')], db_index=True, max_length=20)),
                ('order_code', models.CharField(max_length=40, unique=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_orders', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='concessions.concession')),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('display_name', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='concessions.concessionorder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='concessions.concessionvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('combo_concession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='concessions.concession')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concessions.concessionvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='concession',
            index=models.Index(fields=['is_active'], name='concessions_is_acti_d92e21_idx'),
        ),
        migrations.AddConstraint(
            model_name='concessionorder',
            constraint=models.CheckConstraint(condition=models.Q(('order_total__gte', 0)), name='ck_order_total_nonneg'),
        ),
        migrations.AddIndex(
            model_name='concessionvariant',
            index=models.Index(fields=['concession', 'is_active'], name='concessions_concess_24c275_idx'),
        ),
        migrations.AddConstraint(
            model_name='concessionvariant',
            constraint=models.UniqueConstraint(fields=('concession', 'name'), name='uq_variant_concession_name'),
        ),
        migrations.AddConstraint(
            model_name='concessionvariant',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='ck_variant_base_price_nonneg'),
        ),
        migrations.AddIndex(
            model_name='concessionitem',
            index=models.Index(fields=['order', 'id'], name='concessions_order_i_44fe5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='concessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='concessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_item_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='concessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='ck_item_line_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='combocomponent',
            constraint=models.UniqueConstraint(fields=('combo_concession', 'variant'), name='uq_combo_component'),
        ),
        migrations.AddConstraint(
            model_name='combocomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_combo_qty_positive'),
        ),
    ]
