# Generated by Django 6.0.3 on 2026-03-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
