# Generated by Django 6.0.3 on 2026-03-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0002_concession_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='priority',
            field=models.FloatField(default=0.0, help_text='Priority value, from 0.0 to 1.0.'),
        ),
    ]
