# Generated by Django 6.0.3 on 2026-03-18 16:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessions', '0003_concession_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionvariant',
            name='in_combo_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='in-combo price'),
        ),
        migrations.AddConstraint(
            model_name='concessionvariant',
            constraint=models.CheckConstraint(condition=models.Q(('in_combo_price__gte', 0)), name='ck_variant_in_combo_price_nonneg'),
        ),
    ]
