# Generated by Django 6.0.2 on 2026-02-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0003_alter_pointhistory_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_status_snapshot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
