# Generated by Django 6.0.2 on 2026-03-08

from django.db import migrations, models


def populate_seat_label(apps, schema_editor):
    """Copy seat FK data into the new seat_label CharField."""
    Ticket = apps.get_model("bookings", "Ticket")
    for ticket in Ticket.objects.select_related("seat").all():
        if ticket.seat_id:
            ticket.seat_label = f"{ticket.seat.row_char}{ticket.seat.number}"
            ticket.save(update_fields=["seat_label"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_ticket_booking_status_snapshot_and_more"),
        ("cinemas", "0003_alter_showtime_options_cinemaroom_assigned_movies_and_more"),
    ]

    operations = [
        # 1) Drop old unique_together that references "seat"
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        # 2) Add the new seat_label field
        migrations.AddField(
            model_name="ticket",
            name="seat_label",
            field=models.CharField(
                default="",
                help_text="Seat coordinate, e.g. A1, B12",
                max_length=10,
            ),
        ),
        # 3) Populate seat_label from the old FK
        migrations.RunPython(populate_seat_label, migrations.RunPython.noop),
        # 4) Remove the old seat FK
        migrations.RemoveField(
            model_name="ticket",
            name="seat",
        ),
        # 5) Add new unique_together using seat_label
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("showtime", "seat_label")},
        ),
        # 6) Update seat_type_snapshot choices
        migrations.AlterField(
            model_name="ticket",
            name="seat_type_snapshot",
            field=models.CharField(
                choices=[("normal", "Normal"), ("vip", "VIP"), ("couple", "Couple")],
                max_length=20,
            ),
        ),
    ]
