# Generated by Django 6.0.2 on 2026-03-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_seat_label_remove_seat_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('e_wallet', 'E-Wallet'), ('bank_transfer', 'Bank Transfer'), ('vnpay', 'VNPay'), ('momo', 'MoMo')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_ref', models.CharField(max_length=100, unique=True)),
                ('gateway', models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo')], max_length=10)),
                ('amount', models.BigIntegerField(help_text='Amount in VND')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('gateway_response_code', models.CharField(blank=True, default='', max_length=20)),
                ('gateway_txn_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
