# Generated by Django 6.0.2 on 2026-03-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_method_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='promotion',
        ),
    ]
