"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-defaut-key-change-me")
# sample key: django-insecure-y1ghtb_bkgm%a937wh!-7_v6s&cqp!2b0de3bmx9ltq2(ex=&)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.humanize",
    # Third-party Apps
    "import_export",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "drf_spectacular",  # Swagger
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",
    "debug_toolbar",
    # Local Apps
    "apps.core",
    "apps.users.apps.UsersConfig",
    "apps.movies",
    "apps.cinemas",
    "apps.bookings",
    "apps.promotions",
    "apps.contacts",
    "apps.concessions",
    "channels",
    "django_celery_beat",
    # Must be last so it receives post_delete/post_save signals after all other apps
    "django_cleanup.apps.CleanupConfig",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "cinebook_db"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "password"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ======================================
# JAZZMIN ADMIN CUSTOMIZATION
# ======================================

JAZZMIN_SETTINGS = {
    # -------------------------------
    # Branding / General UI Text
    # -------------------------------
    "site_title": "Admin Panel",  # Title shown in browser tab
    "site_header": "My Project Admin",  # Title in the top-left corner
    "site_brand": "CineBook",  # Brand name in the header
    "welcome_sign": "Welcome to the Admin Panel",
    "copyright": "My Company",
    "topmenu_links": [
        {"name": "Statistics", "url": "admin:dashboard", "icon": "fas fa-chart-line"},
        {"model": "contacts.ContactMessage", "name": "Contact"},
        {"app": "bookings"},
        {
            "name": "User Management",
            "url": "/admin/user-management/",
            "icon": "fas fa-users-cog",
        },
    ],
    # -------------------------------
    # Sidebar Behavior
    # -------------------------------
    "show_sidebar": True,  # Show the left sidebar
    "navigation_expanded": False,  # Collapse sidebar by default (changed from True)
    # Hide certain apps completely
    "hide_apps": ["contacts", "bookings"],  # Auth grouped manually in custom links
    "hide_models": ["users.User", "users.UserProfile"],
    "order_with_respect_to": [
        "movies",
        "cinemas",
        "promotions",
        "concessions",
        "users",
    ],
    # -------------------------------
    # Icons for apps and models
    # -------------------------------
    "icons": {
        # -----------------------
        # Booking
        # -----------------------
        "bookings.Booking": "fas fa-ticket-alt",  # ticket purchase
        "bookings.Ticket": "fas fa-receipt",  # payment receipt
        # -----------------------
        # Cinema
        # -----------------------
        "cinemas.CinemaRoom": "fas fa-door-open",  # theater room
        "cinemas.Showtime": "fas fa-clock",  # movie schedule
        # -----------------------
        # Concession (snacks)
        # -----------------------
        "concessions.Concession": "fas fa-cookie",  # snack item
        "concessions.ConcessionVariant": "fas fa-layer-group",  # size / variant
        "concessions.ComboComponent": "fas fa-box-open",  # combo parts
        "concessions.ConcessionOrder": "fas fa-shopping-cart",  # snack order
        "concessions.ConcessionItem": "fas fa-hamburger",  # individual snack
        "concessions.ConcessionCategory": "fas fa-basket-shopping",  # snack categories
        # -----------------------
        # Contact
        # -----------------------
        "contacts.ContactMessage": "fas fa-envelope",
        # -----------------------
        # Movies
        # -----------------------
        "movies.Movie": "fas fa-film",
        "movies.Version": "fas fa-code-branch",  # 2D / 3D / IMAX version
        # -----------------------
        # Promotion
        # -----------------------
        "promotions.GlobalPromoSettings": "fas fa-cogs",
        "promotions.MoviePromotion": "fas fa-film",
        "promotions.FlatPricePromotion": "fas fa-dollar-sign",
        "promotions.PromoRedemption": "fas fa-money-bill-transfer",
        "promotions.Promotion": "fas fa-bullhorn",
        "promotions.UserPromotion": "fas fa-user-tag",
        # -----------------------
        # Token / Auth
        # -----------------------
        "token_blacklist.BlacklistedToken": "fas fa-ban",
        "token_blacklist.OutstandingToken": "fas fa-key",
        # -----------------------
        # Users
        # -----------------------
        "users.PointHistory": "fas fa-coins",
        "users.PointTransaction": "fas fa-exchange-alt",
        "users.UserProfile": "fas fa-id-badge",
        "users.UserPoint": "fas fa-wallet",
        "users.PointRedemptionConfig": "fas fa-cogs",
        "users.User": "fas fa-user",
    },
    # Default fallback icons
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
    # -------------------------------
    # Custom CSS for additional tweaks
    # -------------------------------
    "custom_css": "admin/palette-fixes.css",
    # Disable UI builder in production
    "show_ui_builder": False,
}

# ======================================
# Jazzmin UI Tweaks (Colors, Layout)
# ======================================
JAZZMIN_UI_TWEAKS = {
    # Navbar theme options: navbar-light, navbar-dark
    "navbar": "navbar-light",
    # BootsWatch theme → https://bootswatch.com/
    "theme": "cosmo",
    # Text size controls
    "body_small_text": False,
    # Sidebar layout
    "sidebar_fixed": True,  # Sticky sidebar
    "sidebar_nav_flat_style": True,  # Flat (no borders)
    "sidebar_nav_child_indent": True,  # Indented child items
}


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    # Throttle rates are opt-in per-view via throttle_classes; nothing is
    # applied globally so authenticated endpoints are unaffected.
    "DEFAULT_THROTTLE_RATES": {
        "email_action": "5/hour",  # registration & forgot-password
        "login": "5/m",  # Limit brute-force login attempts
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "CineBook API",
    "DESCRIPTION": "API for Movie Theater Booking System",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True

APPEND_SLASH = True

# Cache — dùng Redis (database 2) để throttle count không bị mất khi runserver reload
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/2"),
    }
}

# Celery
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")

CELERY_TASK_ALWAYS_EAGER = False  # must be False so the worker executes tasks for real
CELERY_TASK_TIME_LIMIT = 60 * 5  # 5 phút
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 4  # 4 phút
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_BEAT_SCHEDULE = {
    "refresh-promotions-is-active-daily": {
        "task": "apps.promotions.tasks.refresh_promotions_is_active",
        "schedule": crontab(hour=0, minute=0),
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]

# ---------------------------------------------------------------------------
# Frontend
# ---------------------------------------------------------------------------
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# ---------------------------------------------------------------------------
# Email
# Use the console backend locally so activation emails are printed to stdout.
# Switch to an SMTP backend in production by setting EMAIL_BACKEND via env.
# ---------------------------------------------------------------------------
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
    )
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "CineBook <noreply@cinebook.com>")

# ---------------------------------------------------------------------------
# VNPay
# ---------------------------------------------------------------------------
VNPAY_TMN_CODE = os.getenv("VNPAY_TMN_CODE", "")
VNPAY_HASH_SECRET_KEY = os.getenv("VNPAY_HASH_SECRET_KEY", "")
VNPAY_RETURN_URL = os.getenv(
    "VNPAY_RETURN_URL", "http://localhost:8000/api/bookings/vnpay-return/"
)

# ---------------------------------------------------------------------------
# MoMo
# ---------------------------------------------------------------------------
MOMO_PARTNER_CODE = os.getenv("MOMO_PARTNER_CODE", "")
MOMO_ACCESS_KEY = os.getenv("MOMO_ACCESS_KEY", "")
MOMO_SECRET_KEY = os.getenv("MOMO_SECRET_KEY", "")
MOMO_ENDPOINT = os.getenv(
    "MOMO_ENDPOINT", "https://test-payment.momo.vn/v2/gateway/api/create"
)
MOMO_RETURN_URL = os.getenv(
    "MOMO_RETURN_URL", "http://localhost:8000/api/bookings/momo-return/"
)
MOMO_IPN_URL = os.getenv("MOMO_IPN_URL", "http://localhost:8000/api/bookings/momo-ipn/")

# Channels & ASGI Configuration
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Assuming default local Redis
        },
    },
}
