# Generated by Django 6.0.2 on 2026-02-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('point_type', models.CharField(choices=[('REDEEM', 'Redeem'), ('ACCUMULATE', 'Accumulate')], help_text='Type of point transaction (Accumulate, Redeem).', max_length=10)),
                ('points_amount', models.IntegerField(help_text='Positive for Accumulate; negative for Redeem.')),
                ('description', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to='bookings.booking')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Point History',
                'verbose_name_plural': 'Point Histories',
                'db_table': 'point_history',
            },
        ),
    ]
