# Generated by Django 6.0.2 on 2026-02-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pointhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pointhistory',
            table=None,
        ),
    ]
