# Generated by Django 6.0.2 on 2026-02-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_pointhistory_created_at_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id']},
        ),
    ]
