# Generated by Django 6.0.2 on 2026-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pointredemptionconfig_pointtransaction_userpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointredemptionconfig',
            name='ratio_earned',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Point earned when payment successful.', max_digits=2),
        ),
    ]
