# Generated by Django 6.0.2 on 2026-03-06 09:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPromoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_discount_percentage', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stacking_order', models.JSONField(default=list, help_text="An ordered list of PromotionType values, e.g. ['USER', 'MOVIE']")),
                ('calculation_method', models.CharField(choices=[('ADDITIVE', 'Additive'), ('COMPOUNDED', 'Compounded')], default='COMPOUNDED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('stacking_rule', models.CharField(choices=[('STACKABLE', 'Stackable'), ('EXCLUSIVE', 'Exclusive')], default='EXCLUSIVE', max_length=20)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(choices=[('USER', 'User'), ('MOVIE', 'Movie')], editable=False, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('target_campaign', models.CharField(blank=True, choices=[('HOLIDAY', 'Holiday'), ('BIRTHDAY', 'Birthday'), ('AGE_RANGE', 'Age range')], max_length=20, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoviePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('stacking_rule', models.CharField(choices=[('STACKABLE', 'Stackable'), ('EXCLUSIVE', 'Exclusive')], default='EXCLUSIVE', max_length=20)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('type', models.CharField(choices=[('USER', 'User'), ('MOVIE', 'Movie')], editable=False, max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('banner_url', models.URLField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('usage_limit', models.PositiveIntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='movies.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
