# Generated by Django 6.0.2 on 2026-03-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_globalpromosettings_userpromotion_moviepromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('USER', 'User'), ('MOVIE', 'Movie')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_items', to='promotions.globalpromosettings')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('settings', 'promotion_type')},
            },
        ),
    ]
