# Generated by Django 6.0.2 on 2026-03-04 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promostackitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoStackItem',
        ),
    ]
