# Generated by Django 6.0.2 on 2026-03-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_delete_promostackitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpromotion',
            name='new_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='moviepromotion',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpromotion',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
