# Generated by Django 6.0.2 on 2026-03-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_userpromotion_new_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpromotion',
            name='new_base_price',
        ),
    ]
