# Generated by Django 6.0.2 on 2026-03-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_remove_userpromotion_new_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20),
        ),
    ]
