# Generated by Django 6.0.2 on 2026-03-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_movie_title_gin_idx_movie_search_title_and_more'),
        ('promotions', '0008_promoredemption_delete_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPricePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('small_description', models.CharField(help_text='Short version shown in the booking UI dropdown.', max_length=150)),
                ('flat_price', models.PositiveIntegerField(help_text='Flat price per seat in VND (e.g. 60000).')),
                ('seat_scope', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('couple', 'Couple'), ('all', 'All Seat Types')], default='all', help_text='Which seat types this flat price applies to.', max_length=10)),
                ('recurring_weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='If set, promotion applies on this weekday every week. Can be combined with a date range to limit the recurrence window.', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Inclusive start date. Leave blank for open-ended start.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Inclusive end date. Leave blank for open-ended end.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cinema_version', models.ForeignKey(blank=True, help_text='Leave blank to apply to all cinema versions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flat_price_promotions', to='movies.version')),
            ],
            options={
                'db_table': 'flat_price_promotion',
                'ordering': ['-created_at'],
            },
        ),
    ]
