# Generated by Django 6.0.2 on 2026-03-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_flat_price_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpricepromotion',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
