# Generated by Django 6.0.2 on 2026-03-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0010_flatpricepromotion_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepromotion',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Automatically managed flag indicating if the promotion is currently active.'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Automatically managed flag indicating if the promotion is currently active.'),
        ),
    ]
