# Generated by Django 6.0.2 on 2026-02-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_seats', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cinema_room',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('format', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cinema_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='cinemas.cinemaroom')),
            ],
            options={
                'db_table': 'showtime',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_char', models.CharField(max_length=1)),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('couple', 'Couple')], max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cinema_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='cinemas.cinemaroom')),
            ],
            options={
                'db_table': 'seat',
                'unique_together': {('cinema_room', 'row_char', 'number')},
            },
        ),
    ]
