# Generated by Django 6.0.2 on 2026-02-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
        ('movies', '0002_rename_actors_movie_casts_rename_rating_movie_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='format',
        ),
        migrations.AddField(
            model_name='showtime',
            name='version_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='showtime', to='movies.version'),
            preserve_default=False,
        ),
    ]
