# Generated by Django 6.0.2 on 2026-03-09 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_remove_seat_capacity_remove_showtime_format_and_more'),
        ('movies', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(db_column='movie_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='movies.movie'),
            preserve_default=False,
        ),
    ]
