# Generated by Django 6.0.2 on 2026-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_remove_seat_capacity_remove_showtime_format_and_more'),
        ('movies', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='cinemaroom',
            name='assigned_movies',
            field=models.ManyToManyField(blank=True, related_name='assigned_rooms', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('couple', 'Couple')], max_length=20),
        ),
    ]
