# Generated by Django 6.0.2 on 2026-03-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_add_seat_label_remove_seat_fk'),
        ('cinemas', '0003_alter_showtime_options_cinemaroom_assigned_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='seat_map',
            field=models.JSONField(blank=True, default=list, help_text='Flat list of seat dicts: [{row, number, type, status}, ...]'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
