# Generated by Django 6.0.2 on 2026-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_add_seathold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
