# Generated by Django 6.0.2 on 2026-03-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0003_remove_showtime_movie_id_showtime_movie'),
        ('cinemas', '0007_remove_pending_status'),
    ]

    operations = [
    ]
