# Generated by Django 6.0.2 on 2026-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_merge_20260309_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
