# Generated by Django 6.0.2 on 2026-03-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_remove_showtime_movie_showtime_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='room_type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=10),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
