# Generated by Django 6.0.2 on 2026-03-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemas", "0010_cinemaroom_room_type_alter_cinemaroom_total_seats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinemaroom",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="cinemaroom",
            name="seat_map",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Seat layout data. Use the visual editor in admin to modify. Each seat has: x, y, kind, type, row, number, endNumber (for couple seats). Couple seats occupy two positions but are stored as one entry.",
            ),
        ),
        migrations.AlterField(
            model_name="cinemaroom",
            name="total_seats",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
