# Generated by Django 6.0.2 on 2026-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Version',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('directors', models.CharField(max_length=255)),
                ('actors', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('languages_subtitles', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('COMING_SOON', 'Coming Soon'), ('NOW_SHOWING', 'Now Showing'), ('ENDED', 'Ended')], max_length=20, null=True)),
                ('rating', models.CharField(blank=True, choices=[('P', 'General'), ('T13', '13+'), ('K', 'Less than 13, parent accompanied'), ('T16', '16+'), ('T18', '18+'), ('C', 'Banned')], max_length=20, null=True)),
                ('versions', models.ManyToManyField(related_name='movies', to='movies.version')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
    ]
