# Generated by Django 6.0.2 on 2026-02-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='casts',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='label',
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
