# Generated by Django 6.0.2 on 2026-02-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_created_at_alter_version_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='movie',
            table='Movie',
        ),
    ]
