# Generated by Django 6.0.2 on 2026-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_file',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
