# Generated by Django 6.0.2 on 2026-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_poster_url_movie_poster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
