# Generated by Django 6.0.2 on 2026-03-13 06:52

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_movie_options"),
    ]

    operations = [UnaccentExtension(), TrigramExtension()]
