# Generated by Django 6.0.2 on 2026-03-13 07:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20260313_1352'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='movie_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
