# Generated by Django 6.0.2 on 2026-03-13 07:44

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_movie_title_gin_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movie_title_gin_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='search_title',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_title'], name='movie_search_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
