# Generated by Django 6.0.2 on 2026-03-17 02:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_movie_movie_title_gin_idx_movie_search_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('email', models.EmailField(max_length=254)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='movies.movie')),
            ],
            options={
                'db_table': 'MovieReminder',
                'unique_together': {('movie', 'email')},
            },
        ),
    ]
