# Generated by Django 6.0.2 on 2026-03-17 04:07

import unicodedata

from django.db import migrations


def populate_search_title(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    for movie in Movie.objects.all():
        if movie.title:
            clean_title = movie.title.replace("Đ", "D").replace("đ", "d")
            normalized = unicodedata.normalize("NFD", clean_title)
            stripped = "".join(
                [c for c in normalized if unicodedata.category(c) != "Mn"]
            )

            movie.search_title = stripped.lower()
            movie.save(update_fields=["search_title"])


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_moviereminder"),
    ]

    operations = []
